# Generated by Django 5.2.16 on 2026-07-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISISRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=100)),
                ('system_id', models.CharField(max_length=60, unique=True)),
                ('router_ips', models.JSONField(default=list)),
                ('prefixes', models.JSONField(default=list)),
                ('prefix_sid', models.IntegerField(blank=True, null=True)),
                ('prefix_sid_ip', models.CharField(blank=True, max_length=50)),
                ('is_pseudonode', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ISISLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.IntegerField(default=10)),
                ('te_metric', models.IntegerField(blank=True, null=True)),
                ('ip_a', models.CharField(blank=True, max_length=50)),
                ('ip_b', models.CharField(blank=True, max_length=50)),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='isis_analyzer.isisrouter')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='isis_analyzer.isisrouter')),
            ],
            options={
                'unique_together': {('node_a', 'node_b')},
            },
        ),
    ]
